# Generated by Django 4.2.1 on 2023-06-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstorage',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
