# Generated by Django 4.2.1 on 2023-07-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_myskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskill',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
