# Generated by Django 4.2.1 on 2023-07-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_myskill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskill',
            name='progress',
            field=models.IntegerField(null=True),
        ),
    ]
