# Generated by Django 4.2.1 on 2023-07-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_myskill_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUpdateContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='projectstorage',
            name='link_github',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
