# Generated by Django 4.2.1 on 2023-07-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_myupdatecontact_stmplib_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myskill',
            name='conoscenza',
        ),
        migrations.RemoveField(
            model_name='myskill',
            name='progress',
        ),
    ]
