# Generated by Django 4.2.1 on 2023-08-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_myskill_conoscenza_remove_myskill_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='myupdatecontact',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='projectstorage',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
