# Generated by Django 4.2.1 on 2023-08-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_myupdatecontact_image_projectstorage_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstorage',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
